# Generated by Django 5.2.1 on 2025-05-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('10th', '10th'), ('12th', '12th')], max_length=4)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
