# Generated by Django 5.2.1 on 2025-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=9999999999, max_length=15),
            preserve_default=False,
        ),
    ]
